# If you want to change this file, please keep the changes in your working
# copy by using
#
#     git update-index --skip-worktree config/database.yml
#
# or just use DATABASE_URL, in which case Rails will happily skip the whole
# file.
#
# See https://github.com/coopdevs/timeoverflow/wiki/Keeping-your-local-files
# for more information
#

defaults: &defaults
  adapter: postgresql
  username: ''  # default is null
#  collation: 'es_ES.UTF-8'
#  ctype: 'es_ES.UTF-8'
#  template: 'template0'
#  encoding: 'UTF8'
  database: ''
  password: ''
  host: ''
  port: 

development:
  <<: *defaults
  

test:
  <<: *defaults
  

staging:
  <<: *defaults
  
production:
  <<: *defaults
  
